package com.justbash.commands.queryengine;

public enum TokenType {
    DOT, PIPE, COMMA, COLON, SEMICOLON,
    LPAREN, RPAREN, LBRACKET, RBRACKET, LBRACE, RBRACE,
    QUESTION, PLUS, MINUS, STAR, SLASH, PERCENT,
    EQ, NE, LT, LE, GT, GE,
    AND, OR, NOT, ALT,
    ASSIGN, UPDATE_ADD, UPDATE_SUB, UPDATE_MUL, UPDATE_DIV, UPDATE_MOD, UPDATE_ALT, UPDATE_PIPE,
    IDENT, NUMBER, STRING,
    IF, THEN, ELIF, ELSE, END,
    AS, TRY, CATCH,
    TRUE, FALSE, NULL,
    REDUCE, FOREACH, LABEL, BREAK, DEF,
    DOTDOT, EOF
}
